### ISSUE TITLE
Finished or abandoned

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaGraphs/StaticGraphs.jl#36]
Is this ready for production, and simply finished, since it relays much on the Graphs package anyway?
Or is this simply abandoned?

In the latter case, is it possible to archive a repo, so this becomes less ambiguous. :)

**Comment by simonschoelly** [comment]
It is ready for production - but as far as I know it does not provide much performance gains compared to SimpleGraph from Graphs.jl

**Comment by ShalokShalom** [comment]
For me, it would be more for security aspect. Thanks
