### ISSUE TITLE
we can improve adjacency_matrix

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/StaticGraphs.jl#8]
for StaticGraphs:

```
adjacency_matrix(g) = SparseMatrixCSC{Bool,UInt32}(nv(g), nv(g), g.f_ind, g.f_vec, ones(Bool, ne(g)*2));
```

for StaticDiGraphs, just remove the `*2`.

**Comment by slyles1001** [comment]
Would it make sense to put this with the other overrides in StaticGraphs.jl? Or, move those to overrides.jl also?

**Comment by sbromberger** [comment]
this belongs in `overrides.jl`, I think.
